site_name: Cheer Supports IOS App Documentation
plugins:
  - search
  - open-in-new-tab

extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/infotus
  # - icon: fontawesome/brands/linkedin
  #   link: https://github.com/infotus
  

copyright: Created by infotus

theme:
  nav:
  - Home: index.md

  - Technical:
    - 'Introduction': '0tech-intro.md'
    - 'Webview': 1webview.md
    - 'Services': 2services.md
    - 'Databases': 3databases.md
    - 'API Documentation': 4api.md
    - 'Functions': 5func.md
    - 'Other': 6other.md

  - Examples: example.md

  - About: 
    - Intrudoction: intro.md  
    - 'License': 'license.md'
    - 'Release Notes': 'release-notes.md'

  name: material
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.prune
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: orange
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: orange
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
