site_name: Cheer Supports IOS App Documentation
plugins:
  - search
  - open-in-new-tab
  - mkdocs-nav-weight:
      section_renamed: false



extra:
  generator: false
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/infotus
  # - icon: fontawesome/brands/linkedin
  #   link: https://github.com/infotus
  

copyright: Made with Material for Mkdocs

theme:
  nav:
  - Home: index.md

  - General:
    - Project Layout: general/layout.md
    - Future of App: general/future.md

  - Technical:
    - technical/tech-intro.md
    - Webview: technical/webview.md
    - Services: 
      - technical/services/services.md
      - Firebase: 
        - technical/firebase/firebaseintro.md
        - Authentication: technical/firebase/auth.md
        - Storage: technical/firebase/storage.md
        - Messaging: technical/firebase/messaging.md
        - Firestore: technical/firebase/firestore.md
      - AWS: technical/aws/1awsintro.md
      - Daily Login Tracking: technical/Services/daily/daily.md
      - Global Chat: technical/Services/chat/chat.md
      - In App Purchase: technical/Services/IAP/iap.md
    
    - Databases: technical/databases.md
    - API Documentation: technical/api.md
    - Functions: technical/func.md
    - Other: technical/other.md

  # - Examples: example.md

  - About: 
    - about/intro.md  
    - License: about/license.md
    - Release Notes : about/release-notes.md

  name: material
  features:
    - navigation.top
    - navigation.tabs
    # - navigation.sections
    # - navigation.expand
    # - navigation.prune
    - navigation.indexes
    # - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: orange
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: orange
      accent: lime

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
